### ISSUE TITLE
Support for the russian language

### ISSUE THREAD

**Issue by aadcg** [mrkkrp/typit#13]
[russian.txt](https://github.com/mrkkrp/typit/files/4183249/russian.txt)

Thank you for your effort in developing typit.el.

I'm learning the russian layout so I tried typit to practice.

I added the russian.txt to the dict folder (find it attached) and started to test. I was failing every word so I thought about setting the input method of the *typit* buffer to russian - (set-input-method "russian-computer"). Sadly that also doesn't fix the problem.

Could you please give give me some hints and perhaps I can fix this myself? Thanks.

**Comment by mrkkrp** [comment]
How did you set the input method? Did you edit actual Emacs Lisp code for that?

**Comment by mrkkrp** [comment]
So the problem here is that `read-char` does not take input method into account, even though we pass `t` for the `inherit-input-method` argument. In other words, if you press `a` you'll get the same ASCII code regardless of whether you have Russian input method enabled or not. Of course the code for Latin `a` does not match whatever Cyrillic letter corresponds to that.

The question is whether or not this behavior is correct. If not, it is a bug to report. If it is not a bug, then we'd need to find a way to translate characters back. Presumably using translation maps associated with different input methods. It appears that we'd need to remember preferred input method per dictionary.

Unfortunately I do not have time to do this work myself, so it is up to you if you would like to take the challenge. I'd start by finding out whether or not `read-char` does the expected thing in this case.

**Comment by aadcg** [comment]
I think I understood what's going on. When we say switching the input-method we must realize that it can be done on the OS or on Emacs.  

Typit does work if the users switch to russian on the OS. That's because the checking happens with `read-char`. So, of course it won't work if I just switch the input method on the typit buffer. All Emacs does is activating the translation maps so that all keybindings still work. That's why I never switch the input method for the OS if I'm inside of Emacs.

So, all is good and I believe we should just let people know that if they want to use typit with russian they have to switch the input-method on the OS level. 

I can send a merge request with the new dict and these instructions if you agree.

On a side note, speed-type works in any of these cases since it makes the check by comparing what gets on the buffer with `aref`.

**Comment by aadcg** [comment]
Not the best attitude IMO. All the best for you dude.

**Comment by mrkkrp** [comment]
@aadcg, no need to be rude. There must be some sort of misunderstanding here, you said

> all is good and I believe we should just let people know that if they want to use typit with russian they have to switch the input-method on the OS level

Since "all is good", I went ahead and merged the #14 which adds the Russian dictionary. Is there anything else you want me to do? If you want to open PR adding any instructions you deem necessary, I'm open to merging it.

In all honesty I do not see what constitutes "not the best attitude" in this case.

**Comment by aadcg** [comment]
Sorry if I sounded rude, it wasn't my intention. 

My opinion is that I should have been given the chance to commit the changes. `russian.txt` is my contribution, and I believe that that should be reflected. I don't take any pride in such a tiny deed of course. Closing the issue and adding the changes that I authored seems awkward, since I've asked clearly on how should we proceed. Perhaps you thought it would be more practical this way, without a pull request (which is totally fine for me), but perhaps it would have made sense to write beforehand.

I asked for your help because it seemed to me that the the functionality wasn't there at all. You elucidated me, and I just stressed the fact that other users might face the same confusion as me (especially when similar software works in another way). 

All is good from my side. Perhaps there's smth to the git/github workflow that I'm missing.

**Comment by mrkkrp** [comment]
OK, I see now. I did not think about authorship. I amended the last commit and set you as the commit author, see d80ff2c3814ab841d7a63899ec6df7a999890824. Regarding adding instructions, as I said, feel free to open a PR, I'm happy to merge it.
